//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGPKalmanFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BGPKalmanFilter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NewDataSet&gt;
        ///  &lt;Table1&gt;
        ///    &lt;countrycode&gt;ALB&lt;/countrycode&gt;
        ///    &lt;country&gt;Albania&lt;/country&gt;
        ///    &lt;currency_unit&gt;Lek&lt;/currency_unit&gt;
        ///    &lt;year&gt;1950&lt;/year&gt;
        ///    &lt;i_cig /&gt;
        ///    &lt;i_xm /&gt;
        ///    &lt;i_xr /&gt;
        ///    &lt;i_outlier /&gt;
        ///    &lt;i_irr /&gt;
        ///  &lt;/Table1&gt;
        ///  &lt;Table1&gt;
        ///    &lt;countrycode&gt;ALB&lt;/countrycode&gt;
        ///    &lt;country&gt;Albania&lt;/country&gt;
        ///    &lt;currency_unit&gt;Lek&lt;/currency_unit&gt;
        ///    &lt;year&gt;1951&lt;/year&gt;
        ///    &lt;i_cig /&gt;
        ///    &lt;i_xm /&gt;
        ///    &lt;i_xr /&gt;
        ///    &lt;i_outlier /&gt;
        ///    &lt;i_irr /&gt;
        ///  &lt;/T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pwt91 {
            get {
                return ResourceManager.GetString("pwt91", resourceCulture);
            }
        }
    }
}
